In [2]:
import pandas as pd
import openpyxl
import requests
import urllib.parse
import os
from dotenv import load_dotenv
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup
import json
import time
from google import genai


load_dotenv()

True

# План
1. Загрузить данные из таблицы
2. Настройка API

In [4]:
df = pd. read_excel('data3.xlsx')

In [5]:
company_names = df['Наименование']

# YANDEX SEARCH

In [4]:
query_text = 'site:rbc.ru Газпром'
FOLDER_ID = 'b1gkscg2shvabpeut8vu'
SEARCH_ENDPOINT = "https://searchapi.api.cloud.yandex.net/v2/web/search"


payload = {
    "query": {
        # указываем тип поиска web
        "searchType": "SEARCH_TYPE_COM",
        # обязательный текст поиска
        "queryText": query_text,
    },
    # управляющие параметры группировки (можно увеличить, если нужно больше результатов)
    "groupSpec": {
        "groupMode": "GROUP_MODE_FLAT",
        "groupsOnPage": 10,
        "docsInGroup": 1
    },
    # формат ответа
    "responseFormat": "FORMAT_HTML",
    # идентификатор вашего каталога/проекта
    "folderId": FOLDER_ID
}

# --------------------------
# 3) HTTP запрос
# --------------------------

headers = {
    "Content-Type": "application/json",
    # Авторизация через Api-Key
    "Authorization": f"Api-Key {os.getenv('YANDEX_SEARCH_API_KEY')}"
}

In [5]:

response = requests.post(SEARCH_ENDPOINT, json=payload, headers=headers)

In [6]:
print(response.text)

{
 "code": 7,
 "message": "Permission denied",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.RequestInfo",
   "requestId": "7c01db6c-dd26-4b54-8b05-ce6b7146e950"
  }
 ]
}

# Найти настоящее название компании

In [6]:
# setup client 
client = genai.Client(api_key='AIzaSyBUfUEeZMSkOVRCIXhK6FcK0rXoBTungnI')
# choose model from client.models.list()
model = 'models/gemini-2.5-flash'

In [7]:
# for each company name i want to find its real name
company_prompt = "Ты опытный аналитик российского рынка. Я дам тебе юридическое название фирмы. Ты должен найти название компании, связанной с этим юридическим лицом. Ответ давай без форматирования и лишних комментариев, только название компании."
def find_company_real_name(company_name):
    max_retries = 3
    retry_delay = 5  # Start with 5 seconds

    for attempt in range(max_retries): # retry logic in case llm is down
            try:
                # Attempt the API call
                response = client.models.generate_content(model=model, contents=company_prompt + company_name)
                return response.text
            
            except exceptions.ResourceExhausted:
                # Handle Rate Limits (429 errors)
                print(f"Quota exceeded. Retrying in {retry_delay}s... (Attempt {attempt+1}/{max_retries})")
                time.sleep(retry_delay)
                retry_delay *= 2  # Wait longer next time
                
            except exceptions.GoogleAPICallError as e:
                # Handle other API errors (Network, Server error)
                print(f"API Error: {e}. Retrying...")
                time.sleep(retry_delay)
                
            except ValueError:
                # Usually triggered if the model blocks content for safety
                print("Content was blocked by safety filters.")
                return "Название не доступно"
                
            except Exception as e:
                print(f"An unexpected error occurred: {e}")
                break # Stop if it's an unknown error (e.g., code syntax)
    return "Название не доступно"

In [8]:
company_names_real = [find_company_real_name(name) for name in company_names]
df['Название компании'] = [company_name_real if len(company_name_real) < 30 else "Название не доступно" for company_name_real in company_names_real]

# Поиск по вакансиям

In [9]:
def find_postings_by_search_term(search_term):
    BASE__URL = "https://api.hh.ru/vacancies"
    page_counter = 1 # starting page
    finished = 0 # indicates that the search is completed
    listings = []
    while finished == 0: # to parse all pages i iterate
        params = {
            "text": search_term,
            "per_page": 100,
            "page": page_counter
        }
        try:
            response = requests.get(BASE__URL, params=params)
            if response.status_code == 200: # if the page is accessed successfully
                if len(response.json()['items']) == 0: #if empty request – stop
                    finished = 1
                else: # if request is returned 
                    page_counter += 1
                    listings.extend(response.json()['items'])
                    time.sleep(5)
            else: # if the page is not accessed
                finished = 1 # stop the loop
        except:
           finished = 1

    return listings

In [10]:
def record_listing_to_df(listing, company_name):
    for item in listing:
        item['request'] = company_name
    return pd.DataFrame(listing)

In [11]:
all_company_names = list(company_names) + [i for i in list(df['Название компании']) if i != "Название недоступно"]
postings_df = pd.DataFrame()
for company_name in all_company_names:
    postings = find_postings_by_search_term(company_name)
    small_df = record_listing_to_df(postings, company_name)
    postings_df = pd.concat([postings_df, small_df], ignore_index=True)

In [12]:
postings_df.to_excel('postings_3.xlsx', index=False)

In [13]:
pd.set_option('display.max_columns', None) # display all columns
postings_df.head() # display first 5 rows

,id,premium,name,department,has_test,response_letter_required,area,salary,salary_range,type,address,response_url,sort_point_distance,published_at,created_at,archived,apply_alternate_url,show_logo_in_search,show_contacts,insider_interview,url,alternate_url,relations,employer,snippet,contacts,schedule,working_days,working_time_intervals,working_time_modes,accept_temporary,fly_in_fly_out_duration,work_format,working_hours,work_schedule_by_days,accept_labor_contract,civil_law_contracts,night_shifts,professional_roles,accept_incomplete_resumes,experience,employment,employment_form,internship,adv_response_url,is_adv_vacancy,adv_context,request,branding,brand_snippet,immediate_redirect_url
0,129946758,False,Менеджер по работе с маркетплейсами,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': None, 'to': 270000, 'currency': 'RUR'...","{'from': None, 'to': 270000, 'currency': 'RUR'...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Москва', 'street': 'Космодамианская ...",None,None,2026-03-05T14:06:31+0300,2026-03-05T14:06:31+0300,False,https://hh.ru/applicant/vacancy_response?vacan...,None,True,None,https://api.hh.ru/vacancies/129946758?host=hh.ru,https://hh.ru/vacancy/129946758,[],"{'id': '3743178', 'name': 'ГИФТ', 'url': 'http...",{'requirement': 'Наличие опыта работы не менее...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False,[],"[{'id': 'ON_SITE', 'name': 'На месте работодат...","[{'id': 'HOURS_8', 'name': '8 часов'}]","[{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}]",False,[],False,"[{'id': '70', 'name': 'Менеджер по продажам, м...",False,"{'id': 'between3And6', 'name': 'От 3 до 6 лет'}","{'id': 'full', 'name': 'Полная занятость'}","{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,"ООО ""Гибрид""",NaN,NaN,NaN
1,130981075,False,Инженер-проектировщик,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...",None,None,"{'id': 'open', 'name': 'Открытая'}","{'city': 'Москва', 'street': 'Тестовская улица...",None,None,2026-03-04T20:09:56+0300,2026-03-04T20:09:56+0300,False,https://hh.ru/applicant/vacancy_response?vacan...,None,False,None,https://api.hh.ru/vacancies/130981075?host=hh.ru,https://hh.ru/vacancy/130981075,[],"{'id': '4910356', 'name': 'Группа Компаний Нац...",{'requirement': 'Высшее профильное образование...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False,[],"[{'id': 'ON_SITE', 'name': 'На месте работодат...","[{'id': 'HOURS_8', 'name': '8 часов'}]","[{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}]",True,[],False,"[{'id': '48', 'name': 'Инженер-конструктор, ин...",False,"{'id': 'between1And3', 'name': 'От 1 года до 3...","{'id': 'full', 'name': 'Полная занятость'}","{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,"ООО ""Гибрид""",NaN,NaN,NaN
2,130799248,False,Графический дизайнер BYD MEGAWATT,None,False,False,"{'id': '2759', 'name': 'Ташкент', 'url': 'http...","{'from': 8000000, 'to': 10000000, 'currency': ...","{'from': 8000000, 'to': 10000000, 'currency': ...","{'id': 'open', 'name': 'Открытая'}","{'city': 'населённый пункт Тарихтешар', 'stree...",None,None,2026-03-10T14:53:41+0300,2026-03-10T14:53:41+0300,False,https://hh.ru/applicant/vacancy_response?vacan...,None,True,None,https://api.hh.ru/vacancies/130799248?host=hh.ru,https://hh.ru/vacancy/130799248,[],"{'id': '9275229', 'name': 'СП ООО UNILAND-MEGA...",{'requirement': 'Уверенное владение: 1.Photosh...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False,[],"[{'id': 'ON_SITE', 'name': 'На месте работодат...","[{'id': 'HOURS_8', 'name': '8 часов'}]","[{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}]",True,[],False,"[{'id': '34', 'name': 'Дизайнер, художник'}]",False,"{'id': 'between1And3', 'name': 'От 1 года до 3...","{'id': 'full', 'name': 'Полная занятость'}","{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,"ООО ""Гибрид""",NaN,NaN,NaN
3,131005688,False,Менеджер по продажам (товарное направление),None,False,True,"{'id': '26', 'name': 'Воронеж', 'url': 'https:...","{'from': 80000, 'to': 160000, 'currency': 'RUR...","{'from': 80000, 'to': 160000, 'currency': 'RUR...","{'id': 'open', 'name': 'Открытая'}","{'city': 'село Новая Усмань', 'street': 'Алмаз...",None,None,2026-03-05T15:02:19+0300,2026-03-05T15:02:19+0300,False,https://hh.ru/applicant/vacancy_response?vacan...,None,True,None,https://api.hh.ru/vacancies/131005688?host=hh.ru,https://hh.ru/vacancy/131005688,[],"{'id': '11777006', 'name': 'Гидро-Пласт', 'url...",{'requirement': 'Опыт продаж от 1 года. Сильны...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],True,[],"[{'id': 'ON_SITE', 'name': 'На месте работодат...","[{'id': 'HOURS_9', 'name': '9 часов'}]","[{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}]",False,"[{'id': 'SELF_EMPLOYED', 'name': 'с самозаняты...",False,"[{'id': '70', 'name': 'Менеджер по продажам, м...",False,"{'id': 'between1And3', 'name': 'От 1 года до 3...","{'id': 'full', 'name': 'Полная занятость'}","{'id': 'FULL', 'name': 'Полная'}",True,None,False,None,"ООО ""Гибрид""",NaN,NaN,NaN
4,130322536,False,Менеджер проектов/КНР,None,False,True,"{'id': '50', 'name': 'Китай', 'url': 'https://...",None,None,"{'id': 'open', 'name': 'Открытая'}","{'city': 'городской округ Чжэнчжоу', 'street':...",None,None,2026-03-09T13:47:29+0300,2026-03-09T13:47:29+0300,False,https://hh.ru/applicant/vacancy_response?vacan...,None,False,None,https://api.hh.ru/vacancies/130322536?host=hh.ru,https://hh.ru/vacancy/130322536,[],"{'id': '4039336', 'name': 'НПП ИНДУСТРИЯ', 'ur...",{'requirement': 'Постоянное нахождение в Китае...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False,[],"[{'id': 'ON_SITE', 'name': 'На месте работодат...","[{'id': 'HOURS_8', 'name': '8 часов'}]","[{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}]",True,[],False,"[{'id': '107', 'name': 'Руководитель проектов'}]",True,"{'id': 'between1And3', 'name': 'От 1 года до 3...","{'id': 'full', 'name': 'Полная занятость'}","{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,"ООО ""Гибрид""",NaN,NaN,NaN

,id,premium,name,department,has_test,response_letter_required,area,salary,salary_range,type,...,employment_form,internship,adv_response_url,is_adv_vacancy,adv_context,request,branding,brand_snippet,immediate_redirect_url,immediate_redirect_vacancy_id
0,130794146,False,Руководитель проектов 1С,None,False,False,"{'id': '1002', 'name': 'Минск', 'url': 'https:...",None,None,"{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,"ООО ""Бизнес-Аналитика""",NaN,NaN,NaN,NaN
1,130577125,False,Технолог по складским операциям / Бизнес-аналитик,None,False,False,"{'id': '2759', 'name': 'Ташкент', 'url': 'http...",None,None,"{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,"ООО ""Бизнес-Аналитика""",NaN,NaN,NaN,NaN
2,130891355,False,Старший бизнес-аналитик (мед.тех),"{'id': 'pwc-1201-tehprakt', 'name': 'Технологи...",False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...",None,None,"{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,"ООО ""Бизнес-Аналитика""","{'type': 'MAKEUP', 'tariff': None}",NaN,NaN,NaN
3,130637746,False,Бизнес-аналитик EME.WMS,None,False,False,"{'id': '1002', 'name': 'Минск', 'url': 'https:...",None,None,"{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,"ООО ""Бизнес-Аналитика""","{'type': 'MAKEUP', 'tariff': None}",NaN,NaN,NaN
4,130241822,False,Бизнес-аналитик (1С),"{'id': '4880-4880-tech', 'name': 'Детский мир....",True,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...",None,None,"{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,"ООО ""Бизнес-Аналитика""","{'type': 'MAKEUP', 'tariff': None}",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116044,129611080,False,Главный специалист по комплексной автоматизаци...,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...",None,None,"{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,Название не доступно,NaN,NaN,NaN,NaN
116045,131147569,False,Ведущий бухгалтер,None,False,False,"{'id': '104', 'name': 'Челябинск', 'url': 'htt...","{'from': 45000, 'to': None, 'currency': 'RUR',...","{'from': 45000, 'to': None, 'currency': 'RUR',...","{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,Название не доступно,"{'type': 'CONSTRUCTOR', 'tariff': 'BASIC'}",NaN,NaN,NaN
116046,130533380,False,Менеджер по работе с маркетплейсом OZON,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 100000, 'to': None, 'currency': 'RUR'...","{'from': 100000, 'to': None, 'currency': 'RUR'...","{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,Название не доступно,"{'type': 'MAKEUP', 'tariff': None}",NaN,NaN,NaN
116047,130990925,False,Консультант по внедрению конвейерной линии сбо...,None,True,False,"{'id': '2', 'name': 'Санкт-Петербург', 'url': ...",None,None,"{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'PROJECT', 'name': 'Проект'}",False,None,False,None,Название не доступно,"{'type': 'MAKEUP', 'tariff': None}",NaN,NaN,NaN
116048,130167751,False,Научный сотрудник (постдок) в Международную ла...,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 140000, 'to': None, 'currency': 'RUR'...","{'from': 140000, 'to': None, 'currency': 'RUR'...","{'id': 'open', 'name': 'Открытая'}",...,"{'id': 'FULL', 'name': 'Полная'}",False,None,False,None,Название не доступно,"{'type': 'CONSTRUCTOR', 'tariff': 'BASIC'}",NaN,NaN,NaN

# Upload key words

In [14]:
keywords_df = pd. read_excel('data.xlsx', sheet_name='keywords')
keywords_raw = list(keywords_df.loc[0])

In [15]:
def parse_keywords(keywords_raw): 
    return keywords_raw.replace('"', '').split(', ')

In [16]:
keywords = [parse_keywords(i) for i in keywords_raw]

In [17]:
keywords_dict = {}
for i in range(len(keywords)):
    group_name = f"Group_{i+1}"
    keywords_dict[group_name] = keywords[i]

# Вывод предложения по ключевому слову

In [ ]:
def return

# Обработка ключевых слов
для каждой компании я сделаю колонку с числом упоминаний

In [18]:
def count_keyword(list_of_companies, keyword, df=postings_df):
    value = 0 # number of occurrences of keyword
    for company in list_of_companies:
        sub_df = df[df['request'] == company]
        string_to_check = str(sub_df.snippet)
        value += string_to_check.count(keyword)
    return value

мне надо по каждому ключевому слову найти число вхождений

In [19]:
for keyword_group in keywords_dict:
    keyword_column_names = [f"{keyword_group}_{keyword}" for keyword in keywords_dict[keyword_group]]
    for keyword in keywords_dict[keyword_group]:
        keyword_counts_list = []
        for company, real_company_name in zip(df['Наименование'], df['Название компании']):
            keyword_counts_list.append(count_keyword([company, real_company_name], keyword))
        df[f"{keyword_group}_{keyword}"] = keyword_counts_list
    df[keyword_group] = df[keyword_column_names].sum(axis=1)

/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list
/var/folders/s6/2cb6sfpn54q48xnzlvd12qz00000gn/T/ipykernel_43674/3742842933.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{keyword_group}_{keyword}"] = keyword_counts_list

In [36]:
sum(df.Group_11)

0

In [ ]:
keywords

NameError: name 'keywords' is not defined